import express from "express";
import morgan from "morgan";
import cors from "cors";
const app = express();
import imagenRoutes from "./routes/Imagen.routes";
app.use(morgan("dev"));
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(cors());
app.use(imagenRoutes);
export default app;
